# Generated by Django 4.1.3 on 2022-12-05 14:41

import core.models
from django.db import migrations, models


def gen_hint_keys(apps, schema_editor):
    QRCode = apps.get_model("core", "qrcode")
    for qr in QRCode.objects.all():
        qr.key = core.models.generate_hint_key()
        qr.save(update_fields=["key"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_user_chosen"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="key",
            field=models.CharField(
                default=core.models.generate_hint_key,
                max_length=64,
                null=True,
            ),
        ),
        migrations.RunPython(gen_hint_keys, lambda apps, schema_editor: None),
    ]
