# Generated by Django 4.1.3 on 2022-12-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0008_alter_invite_code_alter_qrcode_key_alter_team_name",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="solo",
            field=models.BooleanField(default=False),
        ),
    ]
