# Generated by Django 4.1.3 on 2022-12-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_team_solo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hint",
            name="hint",
            field=models.TextField(
                help_text="Hint for the QR code, create at least two, preferably three",
                max_length=1024,
            ),
        ),
    ]
