# Generated by Django 4.1.3 on 2022-12-08 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_hint_hint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hint",
            options={
                "permissions": [("view_before_cutoff", "Play game before cutoff")]
            },
        ),
    ]
