# Generated by Django 4.1.4 on 2022-12-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_user_chosen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="completed_qr_codes",
        ),
        migrations.RemoveField(
            model_name="team",
            name="current_qr_code",
        ),
        migrations.AddField(
            model_name="team",
            name="current_qr_i",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
