# Generated by Django 4.1.3 on 2022-12-12 23:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_logicpuzzlehint_alter_qrcode_notes"),
        ("core", "0013_remove_team_completed_qr_codes_and_more"),
    ]

    operations = []
