# Generated by Django 4.1.13 on 2023-12-03 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_qrcode_key_hunt_logicpuzzlehint_belongs_to_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="hunt",
            name="form_in_ending_text",
        ),
        migrations.RenameField(
            model_name="hunt",
            old_name="team_size",
            new_name="max_team_size",
        ),
        migrations.AlterField(
            model_name="hunt",
            name="early_access_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users that can access this hunt before it starts",
                related_name="early_access_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
