# Generated by Django 4.1.13 on 2023-12-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_hunt_remove_team_is_active_remove_user_team_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logicpuzzlehint",
            name="qr_index",
            field=models.IntegerField(
                help_text="The index of the QR code that this hint is for, that is everyone on their nth QR code will get same same hint (starting from 1)"
            ),
        ),
        migrations.AddConstraint(
            model_name="logicpuzzlehint",
            constraint=models.UniqueConstraint(
                fields=("qr_index", "hunt"), name="unique_qr_index_name_per_hunt"
            ),
        ),
    ]
