# Generated by Django 4.1.13 on 2023-12-08 01:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_logicpuzzlehint_qr_index_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hint",
            options={},
        ),
    ]
