# Generated by Django 4.1.13 on 2023-12-08 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
teams = []

def migrate_teams_p1(apps, schema_editor):
    # Deletes all Team objects and write them
    Team = apps.get_model("core", "qrcode")
    for team in Team.objects.all():
        teams.append(team.__dict__)
        team.delete()
    print(teams)
    
    
def migrate_teams_p2(apps, schema_editor):
    # Creates
    Team = apps.get_model("core", "Team")
    Team.bulk_create(teams)
    print(f"added {len(teams)}")



class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_logicpuzzlehint_qr_index_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hint",
            options={},
        ),
        migrations.AddField(
            model_name="qrcode",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.team"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "team")},
            },
        ),
        migrations.RunPython(migrate_teams_p1, migrate_teams_p2),
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="teams",
                related_query_name="teams",
                through="core.TeamMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(migrate_teams_p2, migrate_teams_p1),
    ]
