# Generated by Django 4.1.13 on 2023-12-03 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_hunt_middle_locations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hunt",
            old_name="early_access_users",
            new_name="testers",
        ),
        migrations.AlterField(
            model_name="hunt",
            name="testers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users that can access this hunt before it starts as well as after",
                related_name="testers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
