# Generated by Django 4.1.13 on 2023-12-10 03:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_alter_hint_options_qrcode_created_at_teammembership_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="solo",
        ),
    ]
