# Generated by Django 4.1.13 on 2023-12-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_remove_team_solo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="send_to_admin",
            field=models.BooleanField(
                default=False,
                help_text="If when a user scans a QR code, they should be sent to the admin page instead of the hint page. Useful for debugging.",
            ),
        ),
    ]
