# Generated by Django 4.1.13 on 2025-11-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_user_send_to_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hunt",
            name="path_length",
            field=models.PositiveSmallIntegerField(
                default=13,
                help_text="Length of the path: The amount of codes each team will have to find before the end. (not including start/end)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="send_to_admin",
            field=models.BooleanField(
                default=False,
                help_text="If when a user scans a QR code, they should be sent to the admin page instead of the hint page. Useful for debugging. User must be staff. (is_staff)",
            ),
        ),
    ]
