# Generated by Django 4.1.13 on 2023-12-05 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_hunt_ending_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="team",
        ),
        migrations.AddField(
            model_name="hunt",
            name="allow_creation_post_start",
            field=models.BooleanField(
                default=False,
                help_text="Allow users to create teams after the hunt has started",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="teams",
                related_query_name="teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
