# Generated by Django 4.1.3 on 2022-12-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_qrcode_short_alter_invite_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chosen",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
