# Generated by Django 4.1.3 on 2022-12-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_user_chosen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="chosen",
            field=models.BooleanField(default=False),
        ),
    ]
