# Generated by Django 4.1.3 on 2022-12-05 19:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_qrcode_code_alter_invite_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="code",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="key",
            field=models.CharField(
                default=core.models.generate_hint_key, max_length=64, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
