# Generated by Django 4.1.3 on 2022-12-13 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_merge_20221212_1857"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hint",
            options={"permissions": [("view_before_start", "Play game before start")]},
        ),
        migrations.AlterField(
            model_name="invite",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invites",
                to="core.team",
            ),
        ),
    ]
