# Generated by Django 4.1.3 on 2022-11-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="metropolis_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="refresh_token",
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
