# Generated by Django 4.1.3 on 2022-12-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="notes",
            field=models.TextField(help_text="Internal notes"),
        ),
    ]
