# Generated by Django 4.1.3 on 2022-11-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_metropolis_id_user_refresh_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hint",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
