# Generated by Django 4.1.3 on 2022-11-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_hint_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
