# Generated by Django 4.1.3 on 2022-11-28 03:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_qrcode_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hint",
            name="hint",
            field=models.CharField(
                help_text="Hint for the QR code, create at least two, preferably three",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="location",
            field=models.CharField(
                help_text="Location of the QR code, be specific, it's admin only",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="users",
            field=models.ManyToManyField(
                help_text="Users that have located this QR code",
                related_name="qr_scanned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
