# Generated by Django 4.1.3 on 2022-11-29 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_hint_hint_alter_qrcode_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("is_open", models.BooleanField(default=False)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="team", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
