# Generated by Django 4.1.3 on 2022-11-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_invite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
