# Generated by Django 4.1.3 on 2022-11-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_team_id_alter_team_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qrcode",
            name="users",
        ),
        migrations.AddField(
            model_name="team",
            name="current_qr_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="completed_qr_codes",
            field=models.ManyToManyField(
                related_name="completed_qr_codes", to="core.qrcode"
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="code",
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
