# Generated by Django 4.1.3 on 2022-11-29 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_qrcode_users_team_current_qr_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="current_qr_code",
            new_name="completed_qr_codes",
        ),
    ]
