# Generated by Django 4.1.3 on 2022-11-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_team_current_qr_code_remove_team_completed_qr_codes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="completed_qr_codes",
            field=models.ManyToManyField(
                blank=True, related_name="completed_qr_codes", to="core.qrcode"
            ),
        ),
    ]
