# Generated by Django 4.1.4 on 2022-12-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_hint_options_alter_invite_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="current_qr_i",
            field=models.IntegerField(default=0),
        ),
    ]
